[package]
name = "_2048"
version = "0.1.0"
authors = ["Andreas Olofsson <ao@blazar.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
raw_tty = "0.1.0"
libc = "0.2.66"